export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const CUSTOMER_ID_GENERATOR = Symbol('CUSTOMER_ID_GENERATOR');
export const ELECTRONIC_SUBMISSION_SETTINGS_REPOSITORY = Symbol(
  'ELECTRONIC_SUBMISSION_SETTINGS_REPOSITORY',
);
export const ELECTRONIC_SIGNATURE_SETTINGS_REPOSITORY = Symbol(
  'ELECTRONIC_SIGNATURE_SETTINGS_REPOSITORY',
);
export const ELECTRONIC_SIGNATURE_MATERIAL_INSPECTOR = Symbol(
  'ELECTRONIC_SIGNATURE_MATERIAL_INSPECTOR',
);
export const INVOICE_ELECTRONIC_EVENT_REPOSITORY = Symbol(
  'INVOICE_ELECTRONIC_EVENT_REPOSITORY',
);
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const INVOICE_ID_GENERATOR = Symbol('INVOICE_ID_GENERATOR');
export const INVOICE_ELECTRONIC_EVENT_ID_GENERATOR = Symbol(
  'INVOICE_ELECTRONIC_EVENT_ID_GENERATOR',
);
export const INVOICE_ITEM_REPOSITORY = Symbol('INVOICE_ITEM_REPOSITORY');
export const INVOICE_ITEM_ID_GENERATOR = Symbol('INVOICE_ITEM_ID_GENERATOR');
export const ISSUER_PROFILE_REPOSITORY = Symbol('ISSUER_PROFILE_REPOSITORY');
export const INVOICE_NUMBERING_SETTINGS_REPOSITORY = Symbol(
  'INVOICE_NUMBERING_SETTINGS_REPOSITORY',
);
export const ELECTRONIC_INVOICE_SIGNER = Symbol('ELECTRONIC_INVOICE_SIGNER');
export const ELECTRONIC_INVOICE_XML_SCHEMA_VALIDATOR = Symbol(
  'ELECTRONIC_INVOICE_XML_SCHEMA_VALIDATOR',
);
export const ELECTRONIC_INVOICE_SUBMISSION_GATEWAY = Symbol(
  'ELECTRONIC_INVOICE_SUBMISSION_GATEWAY',
);
export const SECRET_REFERENCE_RESOLVER = Symbol('SECRET_REFERENCE_RESOLVER');
export const TAX_RATE_REPOSITORY = Symbol('TAX_RATE_REPOSITORY');
export const TAX_RATE_ID_GENERATOR = Symbol('TAX_RATE_ID_GENERATOR');
export const INVOICE_NOTIFICATION_SENDER = Symbol('INVOICE_NOTIFICATION_SENDER');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const PAYMENT_ID_GENERATOR = Symbol('PAYMENT_ID_GENERATOR');
