export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const CUSTOMER_ID_GENERATOR = Symbol('CUSTOMER_ID_GENERATOR');
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const INVOICE_ID_GENERATOR = Symbol('INVOICE_ID_GENERATOR');
export const INVOICE_ITEM_REPOSITORY = Symbol('INVOICE_ITEM_REPOSITORY');
export const INVOICE_ITEM_ID_GENERATOR = Symbol('INVOICE_ITEM_ID_GENERATOR');
