export const PSYCHOLOGY_CLINIC_OPERATIONS_REPOSITORY = Symbol(
  'PSYCHOLOGY_CLINIC_OPERATIONS_REPOSITORY',
);

export const PSYCHOLOGY_CLINIC_ID_GENERATOR = Symbol(
  'PSYCHOLOGY_CLINIC_ID_GENERATOR',
);
