export const PLAN_REPOSITORY = Symbol('PLAN_REPOSITORY');
export const PLAN_ENTITLEMENT_REPOSITORY = Symbol('PLAN_ENTITLEMENT_REPOSITORY');
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const ENTITLEMENT_REPOSITORY = Symbol('ENTITLEMENT_REPOSITORY');
export const SUBSCRIPTION_ID_GENERATOR = Symbol('SUBSCRIPTION_ID_GENERATOR');
export const TENANT_COMMERCIAL_PROVISIONING_REPOSITORY = Symbol(
  'TENANT_COMMERCIAL_PROVISIONING_REPOSITORY',
);
