export const TENANT_REPOSITORY = Symbol('TENANT_REPOSITORY');
export const MEMBERSHIP_REPOSITORY = Symbol('MEMBERSHIP_REPOSITORY');
export const TENANT_ID_GENERATOR = Symbol('TENANT_ID_GENERATOR');
export const MEMBERSHIP_ID_GENERATOR = Symbol('MEMBERSHIP_ID_GENERATOR');
export const MEMBERSHIP_ROLE_REPOSITORY = Symbol('MEMBERSHIP_ROLE_REPOSITORY');
export const TENANT_PROVISIONING_REPOSITORY = Symbol(
  'TENANT_PROVISIONING_REPOSITORY',
);
export const TENANT_ACCESS_REPOSITORY = Symbol('TENANT_ACCESS_REPOSITORY');
