export const TENANT_REPOSITORY = Symbol('TENANT_REPOSITORY');
export const MEMBERSHIP_REPOSITORY = Symbol('MEMBERSHIP_REPOSITORY');
export const TENANT_ID_GENERATOR = Symbol('TENANT_ID_GENERATOR');
export const MEMBERSHIP_ID_GENERATOR = Symbol('MEMBERSHIP_ID_GENERATOR');
export const INVITATION_ID_GENERATOR = Symbol('INVITATION_ID_GENERATOR');
export const MEMBERSHIP_ROLE_REPOSITORY = Symbol('MEMBERSHIP_ROLE_REPOSITORY');
export const TENANT_PROVISIONING_REPOSITORY = Symbol(
  'TENANT_PROVISIONING_REPOSITORY',
);
export const TENANT_ACCESS_REPOSITORY = Symbol('TENANT_ACCESS_REPOSITORY');
export const INVITATION_REPOSITORY = Symbol('INVITATION_REPOSITORY');
export const INVITATION_ACCEPTANCE_REPOSITORY = Symbol(
  'INVITATION_ACCEPTANCE_REPOSITORY',
);
export const INVITATION_EMAIL_SENDER = Symbol('INVITATION_EMAIL_SENDER');
