export const AI_APPROVAL_REQUEST_REPOSITORY = Symbol(
  'AI_APPROVAL_REQUEST_REPOSITORY',
);
export const AI_SUGGESTION_RUN_REPOSITORY = Symbol(
  'AI_SUGGESTION_RUN_REPOSITORY',
);
export const AI_GUARDED_EXECUTION_EVENT_REPOSITORY = Symbol(
  'AI_GUARDED_EXECUTION_EVENT_REPOSITORY',
);
