export const LEAD_REPOSITORY = Symbol('LEAD_REPOSITORY');
export const LEAD_ID_GENERATOR = Symbol('LEAD_ID_GENERATOR');
export const CONVERSATION_THREAD_REPOSITORY = Symbol(
  'CONVERSATION_THREAD_REPOSITORY',
);
export const CONVERSATION_THREAD_ID_GENERATOR = Symbol(
  'CONVERSATION_THREAD_ID_GENERATOR',
);
export const CONVERSATION_MESSAGE_REPOSITORY = Symbol(
  'CONVERSATION_MESSAGE_REPOSITORY',
);
export const CONVERSATION_MESSAGE_ID_GENERATOR = Symbol(
  'CONVERSATION_MESSAGE_ID_GENERATOR',
);
export const CONVERSATION_DELIVERY_EVENT_REPOSITORY = Symbol(
  'CONVERSATION_DELIVERY_EVENT_REPOSITORY',
);
export const CONVERSATION_DELIVERY_EVENT_ID_GENERATOR = Symbol(
  'CONVERSATION_DELIVERY_EVENT_ID_GENERATOR',
);
export const WEBHOOK_EVENT_ENVELOPE_REPOSITORY = Symbol(
  'WEBHOOK_EVENT_ENVELOPE_REPOSITORY',
);
export const WEBHOOK_EVENT_ENVELOPE_ID_GENERATOR = Symbol(
  'WEBHOOK_EVENT_ENVELOPE_ID_GENERATOR',
);
export const WHATSAPP_OUTBOUND_MESSAGE_GATEWAY = Symbol(
  'WHATSAPP_OUTBOUND_MESSAGE_GATEWAY',
);
export const WHATSAPP_MESSAGE_TEMPLATE_REPOSITORY = Symbol(
  'WHATSAPP_MESSAGE_TEMPLATE_REPOSITORY',
);
export const WHATSAPP_MESSAGE_TEMPLATE_ID_GENERATOR = Symbol(
  'WHATSAPP_MESSAGE_TEMPLATE_ID_GENERATOR',
);
export const WHATSAPP_AUTOMATION_RULE_REPOSITORY = Symbol(
  'WHATSAPP_AUTOMATION_RULE_REPOSITORY',
);
export const WHATSAPP_AUTOMATION_RULE_ID_GENERATOR = Symbol(
  'WHATSAPP_AUTOMATION_RULE_ID_GENERATOR',
);
export const OPPORTUNITY_REPOSITORY = Symbol('OPPORTUNITY_REPOSITORY');
export const OPPORTUNITY_ID_GENERATOR = Symbol('OPPORTUNITY_ID_GENERATOR');
