export const TAX_COMPLIANCE_EVENT_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_EVENT_REPOSITORY',
);
export const TAX_COMPLIANCE_ECOMMERCE_EVIDENCE_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_ECOMMERCE_EVIDENCE_REPOSITORY',
);
export const TAX_COMPLIANCE_ACCOUNTANT_REVIEW_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_ACCOUNTANT_REVIEW_REPOSITORY',
);
export const TAX_COMPLIANCE_PURCHASE_EXPENSE_EVIDENCE_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_PURCHASE_EXPENSE_EVIDENCE_REPOSITORY',
);
export const TAX_COMPLIANCE_EVENT_ID_GENERATOR = Symbol(
  'TAX_COMPLIANCE_EVENT_ID_GENERATOR',
);
export const TAX_COMPLIANCE_ACCOUNTANT_REVIEW_ID_GENERATOR = Symbol(
  'TAX_COMPLIANCE_ACCOUNTANT_REVIEW_ID_GENERATOR',
);
export const TAX_COMPLIANCE_WITHHOLDING_DRAFT_EXECUTOR = Symbol(
  'TAX_COMPLIANCE_WITHHOLDING_DRAFT_EXECUTOR',
);
