export const TAX_COMPLIANCE_EVENT_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_EVENT_REPOSITORY',
);
export const TAX_COMPLIANCE_ACCOUNTANT_REVIEW_REPOSITORY = Symbol(
  'TAX_COMPLIANCE_ACCOUNTANT_REVIEW_REPOSITORY',
);
export const TAX_COMPLIANCE_EVENT_ID_GENERATOR = Symbol(
  'TAX_COMPLIANCE_EVENT_ID_GENERATOR',
);
export const TAX_COMPLIANCE_ACCOUNTANT_REVIEW_ID_GENERATOR = Symbol(
  'TAX_COMPLIANCE_ACCOUNTANT_REVIEW_ID_GENERATOR',
);
