export const ECOMMERCE_PRODUCT_DRAFT_REPOSITORY = Symbol(
  'ECOMMERCE_PRODUCT_DRAFT_REPOSITORY',
);
export const ECOMMERCE_PRODUCT_ENTITY_CHANNEL_DRAFT_REPOSITORY = Symbol(
  'ECOMMERCE_PRODUCT_ENTITY_CHANNEL_DRAFT_REPOSITORY',
);
export const ECOMMERCE_PRODUCT_SETUP_REPOSITORY = Symbol(
  'ECOMMERCE_PRODUCT_SETUP_REPOSITORY',
);
export const ECOMMERCE_PRODUCT_ENTITY_REPOSITORY = Symbol(
  'ECOMMERCE_PRODUCT_ENTITY_REPOSITORY',
);
export const ECOMMERCE_ORDER_DRAFT_REPOSITORY = Symbol(
  'ECOMMERCE_ORDER_DRAFT_REPOSITORY',
);
export const ECOMMERCE_ORDER_OPERATIONAL_EVENT_REPOSITORY = Symbol(
  'ECOMMERCE_ORDER_OPERATIONAL_EVENT_REPOSITORY',
);
